### ISSUE TITLE
Windows Installation: Tests Failed by MemoryError

### ISSUE THREAD

**Issue by HengyueZ** [t-brandt/orvara#15]
I am trying to install the package on Windows. After installation, I ran `pytest -sv` from the command line while under the orbit3d directory, but the last two tests failed. The first (the third of all four tests) showed MemoryError, and the second showed PermissionError, saying that another program was using this file. 

I still had around 4 GB of memory when I ran the code, and I have checked that the code was not pushing it to its limit. I am using the Anaconda distribution of Python and Visual C as the C compiler. Do you have any idea of where the issue came from?

Thanks for your help!

**Comment by elena-mitra** [comment]
I have the same issue, FYI

**Comment by t-brandt** [comment]
Parallelization is finicky--I had a separate issue on a new Mac (but it was fine with 1 thread).  I think that addressing this will require a moderate refactoring of the code.  For now, parallelization is only sort of supported, and it doesn't actually help very much with the speed.

**Comment by gmbrandt** [comment]
@HengyueZ and @elena-mitra could you check that the tests succeed on windows using the branch of PR #22 ?

Thank you,

mirek
