### ISSUE TITLE
Start walkers with jitter=0 in a start file

### ISSUE THREAD

**Issue by Yiting206265** [t-brandt/orvara#16]
When the initial guess for the jitter is 0 (not the uncertainty), the walkers get stuck in local minima instead of exploring all of parameter space, resulting in null jitter. The issue points to line 49 in main.py where np.log10(0) = -inf.

**Comment by t-brandt** [comment]
I believe this is fixed now in the reformat/fits_tables branch.

**Comment by gmbrandt** [comment]
@Yiting206265 when you have a moment, please confirm if it is fixed

**Comment by t-brandt** [comment]
Confirmed fixed.
