### ISSUE TITLE
Nonconvergent results on Windows

### ISSUE THREAD

**Issue by elena-mitra** [t-brandt/orvara#18]
Orbit fitting on the Master branch for an object with a complete RV orbit on Windows results in a non-convergent result although @Yiting206265 is able to get a convergent result with a small error with the same data and parameters. I am running the config file with the DR3 gaia version. I have tried running with jitter=10 and jitter=10e3. I have also tried running between 5,000-100,000 steps with 30 walkers. I have also tried using a start file provided by @Yiting206265.

**Comment by Yiting206265** [comment]
Can someone help Elena troubleshoot when he/she has time? It seems like the
few things we tried that were mentioned didn’t resolve the non-convergent
results she’s getting. I wonder if it’s a windows issue. Any help would be
appreciated.

**Comment by gmbrandt** [comment]
Very weird. @elena-mitra could you upload your start files/data etc to a drop box link and place the link here? I can take a look. It might be a filepath issue or something with how things are specified in config.ini

**Comment by gmbrandt** [comment]
@elena-mitra @Yiting206265 wanted to see if this was still an issue. If so, it would be great to get the input data etc so that I can trouble shoot this. Thanks!
