### ISSUE TITLE
suggestion: priors on RV offsets

### ISSUE THREAD

**Issue by gmbrandt** [t-brandt/orvara#19]
I had a chat with Emily Rickman. in her 2020 work on HD 13724, she placed priors on the RV offsets of Coralie 98 and Coralie 2014 relative to coralie 2007. Because of all the sources fit with those RV 'instruments', the offets are known to within ~10 m/s . Adding this feature would help with mass constraints for e.g. HD 4113 where we basically only have COR measurements, and where letting the RV offsets be 3 totally free parameters will weaken our constraints on the long period brown dwarf.

**Comment by t-brandt** [comment]
I'm pretty uncomfortable with this.  It's possible to implement this, but it's really vulnerable to user mistakes.  And I would be very, very surprised if this prior mattered.  You can check on the difference between the offsets in the chains.

**Comment by gmbrandt** [comment]
Good to know. Yeah I agree that could be a whole can of worms for users. forgetting a prior is set somewhere would be bad.

Although, I thought this would make a difference for sources where the period is long. So the RV curvature is small and so chunking the RV baseline into three effectively makes it so that you are fitting for the curvature with the 3 jitters? Or is the added precision on the mass going to be small? I guess I could find out pretty easily by doing a fit to HD 4113 with the offsets added in before hand...

**Comment by t-brandt** [comment]
If you have a really precise prior on the relative offset, it will help.  I suspect that +/-10 m/s will be useless.

**Comment by gmbrandt** [comment]
ohhhh. Thanks. This just clicked in my head. I realize now that the prior has to be narrower than the resultant (prior free) posterior to make any difference...

Ok closing this issue. Getting a \pm 1 m/s prior on the rv offset is probably impossible.

**Comment by prashant050701** [comment]
Just a generic question: If user is not given the ability to include prior on RV offsets and have a better fit of RV data from 2 telescopes using a different offset. Loading the same data with orvara gives a nicely converged fit but with entirely different offset values.

Maybe these plots would make my case clearer.

![Image](https://github.com/user-attachments/assets/eecd71e2-2eca-489a-a3e4-78fb15282dbd)

<img width="599" alt="Image" src="https://github.com/user-attachments/assets/b5e1c256-98e9-445a-9a50-325aa3583270" />

So wouldn't it make sense to allow prior on offset?
