### ISSUE TITLE
plot_orbit fails to make plots

### ISSUE THREAD

**Issue by trentdupuy** [t-brandt/orvara#26]
(orvara) tdupuy@Trents-MacBook-Pro orvara % plot_orbit test_config.ini                 
Traceback (most recent call last):
  File "/Users/tdupuy/opt/anaconda3/bin/plot_orbit", line 33, in <module>
    sys.exit(load_entry_point('orvara', 'console_scripts', 'plot_orbit')())
  File "/Users/tdupuy/Dropbox/orvara/orvara/main_plotting.py", line 129, in run
    OPs = initialize_plot_options(config)
  File "/Users/tdupuy/Dropbox/orvara/orvara/main_plotting.py", line 86, in initialize_plot_options
    OP.user_xlim = config.get('plotting', 'xlim', fallback=None).split(",")
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by trentdupuy** [comment]
[mcmc_settings]
nplanets = 1
ntemps = 5
nwalkers = 100
nstep = 1000000
use_epoch_astrometry = True

[plotting]
check_convergence = True
burnin = 1000
Astrometry_orbits_plot = True
Relative_separation_plot =True
Position_angle_plot = True
Proper_motion_plot = True
Proper_motion_separate_plots = True
Corner_plot = True
RV_orbits_plot = False
RV_plot = False

**Comment by gmbrandt** [comment]
@trentdupuy are you still having this issue? I think this may have been resolved in a new version of the code.

**Comment by gmbrandt** [comment]
Thanks!
