### ISSUE TITLE
Linux installation failing on pytest with "ImportError while importing test module"

### ISSUE THREAD

**Issue by rbowru** [t-brandt/orvara#32]
Hello, 

I've installed orvara on a linux ubuntu platform following the instructions in the documentation, and I'm running into an issue while running pytest -sv.    I've pasted the error code below (screen shot is also attached).  Do you have any suggestions for how to resolve this? 

Thank you,
Rachel Bowens-Rubin

====

ImportError while importing test module '/home/rbowru/Documents/repo/orvara/orvara/tests/test_main.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../anaconda3/envs/orvara/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
orvara/tests/test_main.py:8: in <module>
    from orvara.main import set_initial_parameters, run, get_priors
orvara/main.py:20: in <module>
    from orvara import orbit
E   ImportError: /home/rbowru/Documents/repo/orvara/orvara/orbit.cpython-39-x86_64-linux-gnu.so: undefined symbol: MAmod
================================================================== short test summary info ===================================================================
ERROR orvara/tests/test_main.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

![image](https://user-images.githubusercontent.com/66432460/134565428-f3a91930-0e21-4c77-896a-b3b91de93aa3.png)

**Comment by nicochunger** [comment]
Hello,
I have the same problem. When I run the pytest -sv, I get exactly the same error message. 
I'm also on Linux

Did you find a solution to this?

**Comment by nicochunger** [comment]
Oh wow, ok. Thanks for the quick reply. It's weird because two colleagues of mine managed to install it without problems also on Linux. I'm wondering if it might be related to the specific distribution of Linux.
Were you using pure Ubuntu? I'm using elementaryOS which is based on Ubuntu but maybe that's the problem.

**Comment by gmbrandt** [comment]
@nicochunger , thank you for giving your solution.
@rbowru did this solve your issue?

**Comment by rbowru** [comment]
I went to installing orvara on a different computer that didn't have this issue, and I've been using the new computer to run orvara fits. I likely won't go back to my original computer that I saw this issue, but thanks for checking in!

**Comment by gmbrandt** [comment]
OK! Thanks for responding!
