### ISSUE TITLE
ERROR: Cannot uninstall 'orvara'

### ISSUE THREAD

**Issue by jiespinozar** [t-brandt/orvara#39]
Hi,

I tried to install orvara by doing: python setup.py install

It failed and now when I try to do: pip install -e .
I get this error: 

![image](https://user-images.githubusercontent.com/64676332/161160795-05da045f-860f-4dc6-8819-ff9655c66c21.png)

The same happens when I try: pip uninstall orvara

How can I uninstall orvara to correctly install it?

**Comment by gmbrandt** [comment]
@jiespinozar hmmm, this is puzzling. I'll try my best to assist with this.

Are you installing orvara into a virtual environment (this is preferred)?

**Comment by gmbrandt** [comment]
Also P.S. ,this looks relevant: https://stackoverflow.com/questions/53807511/pip-cannot-uninstall-package-it-is-a-distutils-installed-project

**Comment by gmbrandt** [comment]
It looks like:
`pip install -e . --ignore-installed orvara`

may work... but -- I highly recommend creating a fresh virtual environment instead (or using a conda env), and then installing orvara into that virtual env. It is much safer, and if anything bad ever happens (like the error you saw), you can always just delete the virtual environment and start anew!

Best,

Mirek

**Comment by jiespinozar** [comment]
I had to uninstall anaconda and reinstall it. Now it is working without problem, but yeah, I should have installed it in a virtualenv. 

Thanks for your help!

Cheers,
Juan Ignacio

**Comment by gmbrandt** [comment]
Great! Thanks for updating this issue with how you solved it!
