### ISSUE TITLE
Proper motion units for plotting

### ISSUE THREAD

**Issue by t-brandt** [t-brandt/orvara#45]
Units of proper motion are now scaled by a factor of 1/365 when plotted--I think the return_proper_motions within orbit.pyx needs to be updated for consistency with the new units to enable acceleration and jerk fittting.

**Comment by gmbrandt** [comment]
Thanks for spotting this! On it.

**Comment by gmbrandt** [comment]
All tests pass on my end with PR #46 and the plotting bug is fixed .  @t-brandt Can you verify, just to be extra careful, that this new branch (https://github.com/t-brandt/orvara/tree/fix/plotting_proper_motion_units) resolves the plotting issue?
