### ISSUE TITLE
config files require both specifying the HGCAfile (dr3 or dr2) AND whether it is dr3 or dr2

### ISSUE THREAD

**Issue by gmbrandt** [t-brandt/orvara#9]
having to specify both leads to potential crosses (e.g. using DR3 HGCA while telling orvara you are using GaiaDR2). We should resolve this because it is ripe to lead to user error.

One fix would be to have it so that GaiaeDR3 or DR2 is set automatically from whatever HGCA catalog you are using. This could be something as simple as a value in the header of the HGCA that is read. Given that the DR3 version of the catalog is not out yet, we can add this header to DR3 (e.g. 'HGCAver = GaiaeDR3') -- and since HGCA DR2 is shipped with the code, we can add 'HGCAver = GaiaDR2' to the header of that catalog and be fine (imo).

**Comment by gmbrandt** [comment]
bringing this to the attention of @t-brandt

**Comment by t-brandt** [comment]
For the new edition of the HGCA I am including a header keyword for the catalog version.  I could add that to the HGCA as packaged here but then this file wouldn't match the one published with the paper.  I could also check for the central epoch of some reference star--maybe that is the way to go?

**Comment by gmbrandt** [comment]
Central epoch works. The header keyword is really nice, and might be less work. If the dr2 version of the hgca is the only one that will be missing that keyword, then could do the following .get() with a dr2 fallback:
hgca[0].header.get('CATVER', 'DR2')

which would have the following behavior
`In [10]: edr3[0].header['CATVER'] = 'eDR3'

In [11]: edr3[0].header.get('CATVER', 'dr2')
Out[11]: 'eDR3'

In [12]: dr2[0].header.get('CATVER', 'dr2')
Out[12]: 'dr2'
`

**Comment by t-brandt** [comment]
Implemented with a np.isclose check on the RA epoch of Hip 1, a failure on both DR2 and EDR3 throws an exception.
